version: "3.9"
services:
  openresty:
    build: .
    container_name: isipage-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./nginx/lua:/etc/nginx/lua:ro
      - ./domains.json:/etc/nginx/domains.json
      - ./data/certbot:/var/lib/certbot
      - ./data/certbot-www:/var/www/certbot
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
