services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    image: isipage-nginx:latest
    container_name: isipage-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # (Opsional) Kalau mau pakai file dari image, HAPUS mount mount di bawah ini.
      # Hanya mount yang memang perlu jadi data (certbot, domains.json, dll)

      - ./data/certbot:/var/lib/certbot
      - ./data/certbot-www:/var/www/certbot
      - ./domains.json:/etc/nginx/domains.json
      - ./nginx/ssl:/etc/nginx/ssl
