version: '3'
services:
  proxy:
    image: openresty/openresty:alpine
    container_name: openresty-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./lua:/etc/nginx/lua
