version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isipage-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/lua:/etc/nginx/lua
      - ./nginx/ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt                # Persist SSL
      - ./certbot-challenge:/var/www/certbot             # Persist challenge
      - ./domains.json:/etc/nginx/domains.json           # Persist domain map
    restart: always
