version: "3"

services:
  nginx:
    build: .
    container_name: isipage-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx
      - acme:/etc/resty-auto-ssl
    restart: unless-stopped

volumes:
  acme:
