version: '3'
services:
  proxy:
    image: openresty/openresty:alpine
    container_name: openresty-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/domains.json:/etc/nginx/domains.json
      - ./nginx/log:/var/log/nginx
      - ./nginx/lua:/etc/nginx/lua
      - ./nginx/ssl:/etc/nginx/ssl
