version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isipage-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/mime.types:/etc/nginx/mime.types
      - ./nginx/lua:/etc/nginx/lua
      - ./nginx/ssl:/etc/nginx/ssl
      # - /etc/letsencrypt:/etc/letsencrypt                # Persist SSL
      # - ./domains.json:/var/domains.json           # Persist domain map
      # - ./nginx/logs:/var/log/nginx
      # - ./certbot-challenge:/var/www/certbot
      # - ./certbot-config:/tmp/certbot-config
      
    restart: always
