version: "3.8"
services:
  isipage:
    build: .
    container_name: isipage-nginx-python
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./domains.json:/etc/nginx/domains.json
      - ./nginx_ssl:/etc/nginx/ssl          # persistent storage untuk ssl per-domain
      - ./www/certbot:/var/www/certbot      # webroot ACME
      - ./nginx_logs:/var/log/nginx
      - ./letsencrypt:/etc/letsencrypt      # certbot native storage
    environment:
      - API_KEY=change_me_super_secret       # ganti sebelum run
      - FLASK_ENV=production
    restart: unless-stopped
